import { useState } from "react";
import { exportProjectToGithub } from "../../services/api";

export default function GitHubExportModal({ projectName, onClose, onExportSuccess }) {
  const [repoName, setRepoName] = useState(projectName || "");
  const [description, setDescription] = useState("Generated by Multi-Agent AI Software Engineering Assistant");
  const [isPrivate, setIsPrivate] = useState(false);
  const [githubToken, setGithubToken] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [result, setResult] = useState(null);
  const [exportStep, setExportStep] = useState("");

  async function handleExport(e) {
    e.preventDefault();
    if (!githubToken.trim() || !repoName.trim()) return;

    setLoading(true);
    setError(null);
    setResult(null);
    setExportStep("Authenticating with GitHub & creating repository...");

    try {
      const data = await exportProjectToGithub({
        projectName,
        githubToken: githubToken.trim(),
        repoName: repoName.trim(),
        description: description.trim(),
        isPrivate,
      });

      setResult(data);
      setExportStep("Success! All files pushed to GitHub.");
      onExportSuccess?.(data);
    } catch (err) {
      setError(err.message || "Failed to export repository to GitHub.");
      setExportStep("");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div
      style={{
        position: "fixed",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        background: "rgba(0, 0, 0, 0.75)",
        backdropFilter: "blur(4px)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 9999,
        padding: "16px",
      }}
      onClick={(e) => {
        if (e.target === e.currentTarget && !loading) onClose();
      }}
    >
      <div
        style={{
          width: "100%",
          maxWidth: "480px",
          background: "var(--ide-surface, #13141f)",
          border: "1px solid var(--ide-border, #2a2c3d)",
          borderRadius: "12px",
          padding: "24px",
          boxShadow: "0 20px 40px rgba(0, 0, 0, 0.6)",
          color: "var(--ide-text, #e2e8f0)",
          fontFamily: "var(--ide-font, sans-serif)",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "16px" }}>
          <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
            <span style={{ fontSize: "22px" }}>🐙</span>
            <div>
              <h3 style={{ margin: 0, fontSize: "16px", fontWeight: 600, color: "#f8fafc" }}>Export to GitHub</h3>
              <p style={{ margin: 0, fontSize: "12px", color: "var(--ide-text-muted, #94a3b8)" }}>
                Push &quot;{projectName}&quot; directly to a new GitHub repository
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            disabled={loading}
            style={{
              background: "transparent",
              border: "none",
              color: "var(--ide-text-muted, #94a3b8)",
              cursor: "pointer",
              fontSize: "18px",
              padding: "4px",
            }}
          >
            ✕
          </button>
        </div>

        {error && (
          <div
            style={{
              padding: "10px 14px",
              background: "rgba(239, 68, 68, 0.12)",
              border: "1px solid rgba(239, 68, 68, 0.3)",
              borderRadius: "8px",
              color: "#fca5a5",
              fontSize: "12px",
              marginBottom: "16px",
            }}
          >
            ⚠ {error}
          </div>
        )}

        {result ? (
          <div>
            <div
              style={{
                padding: "16px",
                background: "rgba(34, 197, 94, 0.1)",
                border: "1px solid rgba(34, 197, 94, 0.3)",
                borderRadius: "8px",
                textAlign: "center",
                marginBottom: "16px",
              }}
            >
              <div style={{ fontSize: "28px", marginBottom: "8px" }}>🎉</div>
              <div style={{ fontWeight: 600, color: "#4ade80", fontSize: "14px", marginBottom: "4px" }}>
                Repository Created Successfully!
              </div>
              <div style={{ fontSize: "12px", color: "var(--ide-text-muted, #94a3b8)", marginBottom: "12px" }}>
                {result.filesUploaded} files uploaded to GitHub.
              </div>
              {result.repositoryUrl && (
                <a
                  href={result.repositoryUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  style={{
                    display: "inline-flex",
                    alignItems: "center",
                    gap: "6px",
                    background: "#2563eb",
                    color: "#ffffff",
                    padding: "8px 16px",
                    borderRadius: "6px",
                    textDecoration: "none",
                    fontSize: "13px",
                    fontWeight: 500,
                  }}
                >
                  Open on GitHub ↗
                </a>
              )}
            </div>
            <button
              type="button"
              className="ide-btn ide-btn--ghost"
              style={{ width: "100%" }}
              onClick={onClose}
            >
              Close
            </button>
          </div>
        ) : (
          <form onSubmit={handleExport}>
            <div style={{ marginBottom: "14px" }}>
              <label style={{ display: "block", fontSize: "12px", fontWeight: 500, marginBottom: "6px" }}>
                GitHub Personal Access Token (PAT) <span style={{ color: "#ef4444" }}>*</span>
              </label>
              <input
                type="password"
                className="ide-input"
                style={{ width: "100%", boxSizing: "border-box" }}
                placeholder="ghp_xxxxxxxxxxxxxxxxxxxx"
                value={githubToken}
                onChange={(e) => setGithubToken(e.target.value)}
                required
                disabled={loading}
              />
              <span style={{ fontSize: "11px", color: "var(--ide-text-muted, #94a3b8)", display: "block", marginTop: "4px" }}>
                Needs <code style={{ color: "#818cf8" }}>repo</code> scope. Tokens are never saved or stored server-side.
              </span>
            </div>

            <div style={{ marginBottom: "14px" }}>
              <label style={{ display: "block", fontSize: "12px", fontWeight: 500, marginBottom: "6px" }}>
                Repository Name <span style={{ color: "#ef4444" }}>*</span>
              </label>
              <input
                type="text"
                className="ide-input"
                style={{ width: "100%", boxSizing: "border-box" }}
                value={repoName}
                onChange={(e) => setRepoName(e.target.value)}
                required
                disabled={loading}
              />
            </div>

            <div style={{ marginBottom: "14px" }}>
              <label style={{ display: "block", fontSize: "12px", fontWeight: 500, marginBottom: "6px" }}>
                Description (optional)
              </label>
              <input
                type="text"
                className="ide-input"
                style={{ width: "100%", boxSizing: "border-box" }}
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                disabled={loading}
              />
            </div>

            <div style={{ marginBottom: "20px" }}>
              <label style={{ display: "block", fontSize: "12px", fontWeight: 500, marginBottom: "6px" }}>
                Visibility
              </label>
              <div style={{ display: "flex", gap: "16px", fontSize: "13px" }}>
                <label style={{ display: "flex", alignItems: "center", gap: "6px", cursor: "pointer" }}>
                  <input
                    type="radio"
                    name="visibility"
                    checked={!isPrivate}
                    onChange={() => setIsPrivate(false)}
                    disabled={loading}
                  />
                  Public
                </label>
                <label style={{ display: "flex", alignItems: "center", gap: "6px", cursor: "pointer" }}>
                  <input
                    type="radio"
                    name="visibility"
                    checked={isPrivate}
                    onChange={() => setIsPrivate(true)}
                    disabled={loading}
                  />
                  Private
                </label>
              </div>
            </div>

            {loading && exportStep && (
              <div style={{ marginBottom: "14px", fontSize: "12px", color: "#818cf8", textAlign: "center" }}>
                ⏳ {exportStep}
              </div>
            )}

            <div style={{ display: "flex", gap: "10px", justifyContent: "flex-end" }}>
              <button
                type="button"
                className="ide-btn ide-btn--ghost"
                onClick={onClose}
                disabled={loading}
              >
                Cancel
              </button>
              <button
                type="submit"
                className="ide-btn ide-btn--primary"
                disabled={loading || !githubToken.trim() || !repoName.trim()}
              >
                {loading ? "Exporting…" : "Export to GitHub"}
              </button>
            </div>
          </form>
        )}
      </div>
    </div>
  );
}
