"""Coder Agent node for generating source code implementations."""

import logging
from config.llm import invoke_with_retry
from graph.state import AgentState
from agents.utils import add_log, get_agent_llm, get_agent_llm_label, strip_code_fence

logger = logging.getLogger(__name__)

CODER_PROMPT_TEMPLATE = """You are a Principal Software Engineer.
Write clean, modern, fully functional code for the following file path in the project.

User Request: "{user_prompt}"
Tech Stack: "{tech_stack}"
Target File Path: "{file_path}"
Other Files in Project: {file_paths}

Return ONLY the complete code content for "{file_path}". Do not include markdown code block syntax if possible, or wrap entirely in a ``` block.
"""


def _get_fallback_code(file_path: str, user_prompt: str) -> str:
    """Generate functional placeholder code when no LLM key is configured."""
    if file_path.endswith(".html"):
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{user_prompt.title()}</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="container">
        <header>
            <h1>{user_prompt.title()}</h1>
            <p>Generated by Multi-Agent AI Software Engineering Assistant</p>
        </header>
        <main id="app">
            <div class="card">
                <h2>Application Control</h2>
                <button id="actionBtn" class="btn">Execute Action</button>
                <div id="output" class="output-box">Ready...</div>
            </div>
        </main>
    </div>
    <script src="app.js"></script>
</body>
</html>
"""
    elif file_path.endswith(".css"):
        return """* {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}

body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    background: #0f172a;
    color: #f8fafc;
    min-height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 2rem;
}

.container {
    max-width: 800px;
    width: 100%;
}

header {
    text-align: center;
    margin-bottom: 2rem;
}

header h1 {
    font-size: 2.5rem;
    color: #38bdf8;
    margin-bottom: 0.5rem;
}

.card {
    background: #1e293b;
    border-radius: 12px;
    padding: 2rem;
    box-shadow: 0 10px 25px rgba(0,0,0,0.3);
}

.btn {
    background: #3b82f6;
    color: #fff;
    border: none;
    padding: 0.75rem 1.5rem;
    font-size: 1rem;
    border-radius: 8px;
    cursor: pointer;
    transition: background 0.2s ease;
}

.btn:hover {
    background: #2563eb;
}

.output-box {
    margin-top: 1rem;
    padding: 1rem;
    background: #0f172a;
    border-radius: 6px;
    border: 1px solid #334155;
    font-family: monospace;
}
"""
    elif file_path.endswith(".js"):
        return f"""// Generated application logic for {user_prompt}
document.addEventListener('DOMContentLoaded', () => {{
    const btn = document.getElementById('actionBtn');
    const output = document.getElementById('output');
    
    let count = 0;
    if (btn && output) {{
        btn.addEventListener('click', () => {{
            count++;
            output.textContent = `Action executed ${{count}} times at ${{new Date().toLocaleTimeString()}}`;
        }});
    }}
}});
"""
    else:
        return f"// Source file: {file_path}\n// Generated for: {user_prompt}\n"


def coder_agent(state: AgentState) -> dict:
    """Executes code generation for all planned files."""
    logs = add_log(state.get("logs", []), "CoderAgent", "started", "Generating source code for project files...")

    user_prompt = state.get("user_prompt", "")
    tech_stack = state.get("tech_stack", "HTML/CSS/JS")
    architecture = state.get("architecture", {})
    file_paths = architecture.get("file_paths", ["index.html", "styles.css", "app.js"])

    llm = get_agent_llm(state, temperature=0.2)
    generated_files = {}
    used_live_llm = llm is not None

    for file_path in file_paths:
        if llm is None:
            generated_files[file_path] = _get_fallback_code(file_path, user_prompt)
        else:
            try:
                raw_code = invoke_with_retry(
                    llm,
                    CODER_PROMPT_TEMPLATE.format(
                        user_prompt=user_prompt,
                        tech_stack=tech_stack,
                        file_path=file_path,
                        file_paths=file_paths,
                    ),
                )
                generated_files[file_path] = strip_code_fence(raw_code)
            except Exception as e:
                logger.error(f"Error coding {file_path}: {e}")
                generated_files[file_path] = _get_fallback_code(file_path, user_prompt)

    mode_label = get_agent_llm_label(state) if used_live_llm else "mock templates"
    logs = add_log(
        logs,
        "CoderAgent",
        "completed",
        f"Generated code for {len(generated_files)} files via {mode_label}.",
    )
    return {
        "files": generated_files,
        "logs": logs,
        "current_step": "coded",
    }
