"""Coder Agent node for generating source code implementations."""

import logging
from config.llm import FallbackLLM, invoke_with_retry, is_quota_error
from config.settings import settings
from graph.state import AgentState
from agents.utils import (
    add_log,
    get_agent_llm,
    llm_label,
    parse_multi_file_response,
    strip_code_fence,
)

logger = logging.getLogger(__name__)

CODER_PROMPT_TEMPLATE = """You are a Principal Software Engineer.
Write clean, modern, fully functional code for EVERY file listed below, in a single response.

User Request: "{user_prompt}"
Tech Stack: "{tech_stack}"
Files To Write: {file_paths}

The files must work together as one application — keep element ids, imports, and function names
consistent across them.

Format the response exactly like this, once per file and nothing else:

FILE: path/of/file
```
<complete file content>
```
"""

SINGLE_FILE_PROMPT_TEMPLATE = """You are a Principal Software Engineer.
Write the complete content of ONE file of a project.

User Request: "{user_prompt}"
Tech Stack: "{tech_stack}"
All Files In The Project: {file_paths}
File To Write Now: {file_path}

The file must work with the others — keep element ids, imports, and function names consistent
with the file names listed above.

Return only the content of {file_path} inside a single code fence, with no commentary.
"""

# Small local models lose the output format part-way through a multi-file response, but they
# handle one file at a time — and a local provider has no request quota to spend on the extra
# calls. Cloud providers keep the single-call path, where requests are the scarce resource.
LOCAL_PROVIDERS = {"ollama"}


def one_call_per_file(llm: FallbackLLM) -> bool:
    """Whether this model should write one file per call instead of all files in one."""
    mode = settings.coder_file_mode.lower()
    if mode == "file":
        return True
    if mode == "batch":
        return False
    return llm.candidates[0][0] in LOCAL_PROVIDERS


def _generate_file_by_file(
    llm: FallbackLLM,
    file_paths: list[str],
    user_prompt: str,
    tech_stack: str,
) -> tuple[dict[str, str], BaseException | None]:
    """One call per file, so a weak model only has to hold one file's format at a time."""
    generated: dict[str, str] = {}
    last_error: BaseException | None = None

    for file_path in file_paths:
        try:
            raw = invoke_with_retry(
                llm,
                SINGLE_FILE_PROMPT_TEMPLATE.format(
                    user_prompt=user_prompt,
                    tech_stack=tech_stack,
                    file_paths=file_paths,
                    file_path=file_path,
                ),
            )
        except Exception as error:
            logger.warning("Coder Agent failed on %s: %s", file_path, error)
            last_error = error
            continue

        # The model is asked for bare content, but often labels it anyway.
        content = parse_multi_file_response(raw).get(file_path) or strip_code_fence(raw)
        if content:
            generated[file_path] = content

    return generated, last_error


def _get_fallback_code(file_path: str, user_prompt: str) -> str:
    """Generate functional placeholder code when no LLM key is configured."""
    if file_path.endswith(".html"):
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{user_prompt.title()}</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="container">
        <header>
            <h1>{user_prompt.title()}</h1>
            <p>Generated by Multi-Agent AI Software Engineering Assistant</p>
        </header>
        <main id="app">
            <div class="card">
                <h2>Application Control</h2>
                <button id="actionBtn" class="btn">Execute Action</button>
                <div id="output" class="output-box">Ready...</div>
            </div>
        </main>
    </div>
    <script src="app.js"></script>
</body>
</html>
"""
    elif file_path.endswith(".css"):
        return """* {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}

body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    background: #0f172a;
    color: #f8fafc;
    min-height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 2rem;
}

.container {
    max-width: 800px;
    width: 100%;
}

header {
    text-align: center;
    margin-bottom: 2rem;
}

header h1 {
    font-size: 2.5rem;
    color: #38bdf8;
    margin-bottom: 0.5rem;
}

.card {
    background: #1e293b;
    border-radius: 12px;
    padding: 2rem;
    box-shadow: 0 10px 25px rgba(0,0,0,0.3);
}

.btn {
    background: #3b82f6;
    color: #fff;
    border: none;
    padding: 0.75rem 1.5rem;
    font-size: 1rem;
    border-radius: 8px;
    cursor: pointer;
    transition: background 0.2s ease;
}

.btn:hover {
    background: #2563eb;
}

.output-box {
    margin-top: 1rem;
    padding: 1rem;
    background: #0f172a;
    border-radius: 6px;
    border: 1px solid #334155;
    font-family: monospace;
}
"""
    elif file_path.endswith(".js"):
        return f"""// Generated application logic for {user_prompt}
document.addEventListener('DOMContentLoaded', () => {{
    const btn = document.getElementById('actionBtn');
    const output = document.getElementById('output');
    
    let count = 0;
    if (btn && output) {{
        btn.addEventListener('click', () => {{
            count++;
            output.textContent = `Action executed ${{count}} times at ${{new Date().toLocaleTimeString()}}`;
        }});
    }}
}});
"""
    else:
        return f"// Source file: {file_path}\n// Generated for: {user_prompt}\n"


def coder_agent(state: AgentState) -> dict:
    """Executes code generation for all planned files."""
    logs = add_log(state.get("logs", []), "CoderAgent", "started", "Generating source code for project files...")

    user_prompt = state.get("user_prompt", "")
    tech_stack = state.get("tech_stack", "HTML/CSS/JS")
    architecture = state.get("architecture", {})
    file_paths = architecture.get("file_paths", ["index.html", "styles.css", "app.js"])

    llm = get_agent_llm(state, temperature=0.2, role="coder")

    if llm is None:
        generated_files = {path: _get_fallback_code(path, user_prompt) for path in file_paths}
        logs = add_log(
            logs,
            "CoderAgent",
            "completed",
            f"Generated code for {len(generated_files)} files via mock templates.",
        )
        return {"files": generated_files, "logs": logs, "current_step": "coded"}

    per_file = one_call_per_file(llm)

    if per_file:
        generated_files, error = _generate_file_by_file(llm, file_paths, user_prompt, tech_stack)
        if not generated_files and error is not None:
            logger.error(f"Coder Agent error: {error}")
            status = "quota_exceeded" if is_quota_error(error) else "error"
            logs = add_log(logs, "CoderAgent", status, f"Code generation failed: {error}")
            return {"error": str(error), "logs": logs, "current_step": "coding_failed"}
    else:
        try:
            raw = invoke_with_retry(
                llm,
                CODER_PROMPT_TEMPLATE.format(
                    user_prompt=user_prompt,
                    tech_stack=tech_stack,
                    file_paths=file_paths,
                ),
            )
        except Exception as e:
            logger.error(f"Coder Agent error: {e}")
            status = "quota_exceeded" if is_quota_error(e) else "error"
            logs = add_log(logs, "CoderAgent", status, f"Code generation failed: {e}")
            return {"error": str(e), "logs": logs, "current_step": "coding_failed"}

        generated_files = parse_multi_file_response(raw)

    missing = [path for path in file_paths if path not in generated_files]

    for path in missing:
        generated_files[path] = _get_fallback_code(path, user_prompt)

    strategy = f"{len(file_paths)} calls" if per_file else "one call"
    message = (
        f"Generated code for {len(generated_files)} files in {strategy} "
        f"via {llm_label(llm, state)}."
    )
    if missing:
        message += f" Used templates for {len(missing)} file(s) the model did not return: {', '.join(missing)}."

    logs = add_log(logs, "CoderAgent", "warning" if missing else "completed", message)
    return {
        "files": generated_files,
        "logs": logs,
        "current_step": "coded",
    }
