"""Doc Agent node for generating project documentation and README."""

import logging
from config.llm import get_llm
from graph.state import AgentState
from agents.utils import add_log

logger = logging.getLogger(__name__)

DOC_PROMPT_TEMPLATE = """You are a Technical Writer.
Generate a comprehensive, beautiful README.md file for the generated application.

Project Name: "{project_name}"
User Prompt: "{user_prompt}"
Tech Stack: "{tech_stack}"
Generated Files: {file_paths}

Include:
1. Overview & Features
2. Tech Stack used
3. Installation & Run instructions
4. Project Structure

Return ONLY the raw Markdown content for README.md.
"""


def doc_agent(state: AgentState) -> dict:
    """Executes documentation synthesis for the generated project."""
    logs = add_log(state.get("logs", []), "DocAgent", "started", "Generating project documentation and README.md...")

    project_name = state.get("project_name", "Generated Application")
    user_prompt = state.get("user_prompt", "")
    tech_stack = state.get("tech_stack", "HTML/CSS/JS")
    files = state.get("files", {})
    file_paths = list(files.keys())

    llm = get_llm(temperature=0.2)
    if llm is None:
        readme_content = f"""# {project_name.title()}

> Generated by Multi-Agent AI Software Engineering Assistant

## Overview
{user_prompt}

## Technology Stack
- **Tech Stack**: {tech_stack}

## Project Structure
```text
{project_name}/
""" + "\n".join([f"├── {p}" for p in file_paths]) + """
```

## How to Run
1. Open `index.html` in any web browser or use a local HTTP server (e.g. `npx serve .` or Live Server).
"""
    else:
        try:
            response = llm.invoke(DOC_PROMPT_TEMPLATE.format(
                project_name=project_name,
                user_prompt=user_prompt,
                tech_stack=tech_stack,
                file_paths=file_paths,
            ))
            readme_content = response.content if hasattr(response, "content") else str(response)
            if readme_content.startswith("```"):
                lines = readme_content.split("\n")
                if lines[0].startswith("```"):
                    lines = lines[1:]
                if lines and lines[-1].startswith("```"):
                    lines = lines[:-1]
                readme_content = "\n".join(lines)
        except Exception as e:
            logger.error(f"Doc agent error: {e}")
            readme_content = f"# {project_name}\n\n{user_prompt}\n"

    # Add README.md to generated files dictionary as well
    updated_files = dict(files)
    updated_files["README.md"] = readme_content

    logs = add_log(logs, "DocAgent", "completed", "Documentation generated successfully.")
    return {
        "documentation": readme_content,
        "files": updated_files,
        "logs": logs,
        "current_step": "completed",
    }
