"""Doc Agent node for generating project documentation and README.

The README is assembled from state the earlier agents already produced (plan, architecture,
QA results, file tree), so documenting a project costs no additional provider quota.
"""

import logging

from graph.state import AgentState
from agents.utils import add_log

logger = logging.getLogger(__name__)

RUN_INSTRUCTIONS = {
    "html": "Open `index.html` in a browser, or serve the folder with `npx serve .`.",
    "python": "Install dependencies with `pip install -r requirements.txt`, then run `python main.py`.",
    "node": "Install dependencies with `npm install`, then start the app with `npm start`.",
}


def _run_instructions(tech_stack: str, file_paths: list[str]) -> str:
    """Pick run instructions that match the generated files."""
    stack = tech_stack.lower()

    if any(path.endswith(".py") for path in file_paths) or "python" in stack:
        return RUN_INSTRUCTIONS["python"]
    if "package.json" in file_paths or "node" in stack or "react" in stack or "express" in stack:
        return RUN_INSTRUCTIONS["node"]
    return RUN_INSTRUCTIONS["html"]


def _bullets(items: list[str]) -> str:
    return "\n".join(f"- {item}" for item in items) if items else "- _None recorded._"


def _build_readme(state: AgentState, file_paths: list[str]) -> str:
    """Render the project README from the pipeline's own outputs."""
    project_name = state.get("project_name", "Generated Application")
    user_prompt = state.get("user_prompt", "")
    tech_stack = state.get("tech_stack", "HTML/CSS/JS")
    tasks = state.get("tasks", [])
    architecture = state.get("architecture", {})
    review = state.get("review_results", {})

    tree = "\n".join(f"├── {path}" for path in sorted(file_paths))
    issues = review.get("issues", [])
    qa_line = "Passed" if review.get("passed", True) else f"{len(issues)} open issue(s)"

    return f"""# {project_name.replace("-", " ").title()}

> Generated by the Multi-Agent AI Software Engineering Assistant.

## Overview

{user_prompt or "No prompt recorded."}

## Tech Stack

{tech_stack}

{architecture.get("design_notes", "")}

## Implementation Plan

{_bullets(tasks)}

## Project Structure

```text
{project_name}/
{tree}
```

## How to Run

{_run_instructions(tech_stack, file_paths)}

## Quality Review

- Static review: {qa_line}
{_bullets(issues) if issues else ""}
""".rstrip() + "\n"


def doc_agent(state: AgentState) -> dict:
    """Executes documentation synthesis for the generated project."""
    logs = add_log(state.get("logs", []), "DocAgent", "started", "Generating project documentation and README.md...")

    files = state.get("files", {})
    readme_content = _build_readme(state, [path for path in files if not path.startswith("README")])

    updated_files = dict(files)
    updated_files["README.md"] = readme_content

    logs = add_log(logs, "DocAgent", "completed", "Documentation generated from the agent pipeline outputs.")

    return {
        "documentation": readme_content,
        "files": updated_files,
        "logs": logs,
        "current_step": "completed",
    }
